spring:
  #数据库连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/esbookmark
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    #Redis使用的数据库
    database: 0
    password: 123456
    #连接超时事件毫秒
    timeout: 18000
    lettuce:
      pool:
        #连接池最大连接数
        max-active: 20
        #最大阻塞等待时间
        max-idle: 5
        #连接池最小空闲连接
        min-idle: 0
  #文件上传的配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
#Mybatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

##阿里云OSS
#aliyun:
#  oss:
#    endpoint: https://oss-cn-hangzhou.aliyuncs.com
#    accessKeyId: LTAI4GCH1vX6DKqJWxd6nEuW
#    accessKeySecret: yBshYweHOpqDuhCArrVHwIiBKpyqSL
#    bucketName: web-tlias
